name: CoderCo Combined

on: [push]

jobs:
  build:
  
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}

    - name: run tests
      run: |
        cd chapter4
        python hello.py
        python -m unittest discover

    - name: notify us if success
      run: echo "Tests passed on ${{ matrix.python-version }}"
      if: success()