name: coderco-secrets-lab
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: test secret
      run: echo "the secret is ${{ secrets.MY_SECRET }}"

  